import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { METRIC_CONTRACT, TOKEN_CONTRACT } from '../src/themes/contract';

const root = fileURLToPath(new URL('..', import.meta.url));

function generateContractMd(): string {
  const lines: string[] = [
    '<!-- Generated by `npm run generate:contract` from src/themes/contract.ts. Do not edit by hand. -->',
    '',
    '# Theme token contract',
    '',
    'Every color, font, and metric a theme can control. A theme JSON file may set any subset of the',
    'tokens below — anything omitted falls back to the base light or dark palette.',
    '',
    '## Colors',
    '',
    '| Token | Description | Default |',
    '| --- | --- | --- |',
  ];
  for (const t of TOKEN_CONTRACT.filter((t) => t.type === 'color')) {
    lines.push(`| \`${t.name}\` | ${t.description} | \`${t.default}\` |`);
  }
  lines.push('', '## Fonts', '', '| Token | Description | Default |', '| --- | --- | --- |');
  for (const t of TOKEN_CONTRACT.filter((t) => t.type === 'font-stack')) {
    lines.push(`| \`${t.name}\` | ${t.description} | \`${t.default}\` |`);
  }
  lines.push(
    '',
    '## Metrics (app-level, not theme-level)',
    '',
    '| Token | Description | Default | Range |',
    '| --- | --- | --- | --- |',
  );
  for (const m of METRIC_CONTRACT) {
    lines.push(`| \`${m.name}\` | ${m.description} | \`${m.default}${m.unit}\` | ${m.min}–${m.max}${m.unit} |`);
  }
  lines.push('');
  return lines.join('\n');
}

function generateSchemaJson(): string {
  const properties: Record<string, unknown> = {};
  for (const t of TOKEN_CONTRACT) {
    properties[t.name] = {
      type: 'string',
      description: t.description,
      default: t.default,
      ...(t.type === 'color'
        ? { pattern: '^(#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})|(rgb|rgba|hsl|hsla|oklch)\\(.*\\))$' }
        : {}),
    };
  }
  const schema = {
    $schema: 'http://json-schema.org/draft-07/schema#',
    title: 'MDReader theme file',
    type: 'object',
    required: ['name'],
    properties: {
      name: { type: 'string', description: 'Display name shown in the theme picker' },
      mode: { type: 'string', enum: ['light', 'dark'], description: 'Badge shown next to the theme name' },
      tokens: {
        type: 'object',
        description: 'Partial map of token name -> value. Omitted tokens inherit from the base palette.',
        properties,
        additionalProperties: false,
      },
    },
    additionalProperties: false,
  };
  return JSON.stringify(schema, null, 2) + '\n';
}

writeFileSync(new URL('./contract.md', `file://${root}`), generateContractMd());
writeFileSync(new URL('./public/theme-schema.json', `file://${root}`), generateSchemaJson());

console.log('Generated contract.md and public/theme-schema.json');
